/**
 * Generates the action icons.
 *
 * Committed as PNGs, but generated by script so the shape can be adjusted
 * without a design tool and without adding a build dependency. Run:
 *   npm run icons
 */

import { deflateSync } from 'node:zlib';
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const OUT_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'icons');
const SIZES = [16, 32, 48, 128];
const SAMPLES = 4; // supersampling per axis

const BACKGROUND = [31, 95, 191];
const TICKET = [255, 255, 255];

/** Distance from a point to a rounded rectangle; negative is inside. */
function roundedRectDistance(px, py, x0, y0, x1, y1, radius) {
  const halfW = (x1 - x0) / 2;
  const halfH = (y1 - y0) / 2;
  const cx = x0 + halfW;
  const cy = y0 + halfH;
  const r = Math.min(radius, halfW, halfH);
  const dx = Math.abs(px - cx) - (halfW - r);
  const dy = Math.abs(py - cy) - (halfH - r);
  const outside = Math.hypot(Math.max(dx, 0), Math.max(dy, 0));
  return outside + Math.min(Math.max(dx, dy), 0) - r;
}

/**
 * A coupon: rounded card, a notch bitten out of each side, and a perforation
 * running down the middle.
 */
function sample(x, y, size) {
  const bgInside = roundedRectDistance(x, y, 0, 0, size, size, size * 0.22) < 0;
  if (!bgInside) return null;

  const inset = size * 0.2;
  const ticket = roundedRectDistance(x, y, inset, inset * 1.35, size - inset, size - inset * 1.35, size * 0.07) < 0;
  if (!ticket) return BACKGROUND;

  const notchRadius = size * 0.1;
  const notchY = size / 2;
  const leftNotch = Math.hypot(x - inset, y - notchY) < notchRadius;
  const rightNotch = Math.hypot(x - (size - inset), y - notchY) < notchRadius;
  if (leftNotch || rightNotch) return BACKGROUND;

  // Perforation: a dashed vertical line, skipped at small sizes where it would
  // just turn the ticket grey.
  if (size >= 32) {
    const onLine = Math.abs(x - size / 2) < Math.max(size * 0.018, 0.6);
    const dash = Math.floor(y / (size * 0.07)) % 2 === 0;
    if (onLine && dash) return BACKGROUND;
  }

  return TICKET;
}

function renderRGBA(size) {
  const pixels = Buffer.alloc(size * size * 4);
  const step = 1 / SAMPLES;

  for (let py = 0; py < size; py += 1) {
    for (let px = 0; px < size; px += 1) {
      let r = 0;
      let g = 0;
      let b = 0;
      let a = 0;

      for (let sy = 0; sy < SAMPLES; sy += 1) {
        for (let sx = 0; sx < SAMPLES; sx += 1) {
          const colour = sample(px + (sx + 0.5) * step, py + (sy + 0.5) * step, size);
          if (!colour) continue;
          r += colour[0];
          g += colour[1];
          b += colour[2];
          a += 255;
        }
      }

      const total = SAMPLES * SAMPLES;
      const offset = (py * size + px) * 4;
      const covered = a / 255;
      if (covered > 0) {
        pixels[offset] = Math.round(r / covered);
        pixels[offset + 1] = Math.round(g / covered);
        pixels[offset + 2] = Math.round(b / covered);
      }
      pixels[offset + 3] = Math.round(a / total);
    }
  }
  return pixels;
}

const CRC_TABLE = (() => {
  const table = new Int32Array(256);
  for (let n = 0; n < 256; n += 1) {
    let c = n;
    for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c;
  }
  return table;
})();

function crc32(buffer) {
  let c = 0xffffffff;
  for (const byte of buffer) c = CRC_TABLE[(c ^ byte) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function chunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([length, body, crc]);
}

function encodePng(size, rgba) {
  const header = Buffer.alloc(13);
  header.writeUInt32BE(size, 0);
  header.writeUInt32BE(size, 4);
  header[8] = 8; // bit depth
  header[9] = 6; // RGBA
  header[10] = 0; // deflate
  header[11] = 0; // adaptive filtering
  header[12] = 0; // no interlace

  const stride = size * 4;
  const raw = Buffer.alloc((stride + 1) * size);
  for (let y = 0; y < size; y += 1) {
    raw[y * (stride + 1)] = 0; // filter: none
    rgba.copy(raw, y * (stride + 1) + 1, y * stride, (y + 1) * stride);
  }

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', header),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

mkdirSync(OUT_DIR, { recursive: true });
for (const size of SIZES) {
  const file = join(OUT_DIR, `icon${size}.png`);
  writeFileSync(file, encodePng(size, renderRGBA(size)));
  console.log(`wrote ${file}`);
}
